### ISSUE TITLE
Possible Non-Square Adjacency Matrix

### ISSUE THREAD

**Issue by xiaotianliu-dartmouth** [twitter-research/feature-propagation#2]
If the edge index somehow does not include the last row or column of the adjacency matrix, the torch.sparse.FloatTensor() may not keep the full dimensionality of the matrix which later will result in error. 
Change [line 39](https://github.com/twitter-research/feature-propagation/blob/de9ec54d5c035abe8d52d6ac4079156cc537e489/src/feature_propagation.py#L39) in feature_propagation.py
`adj = torch.sparse.FloatTensor(edge_index, values=edge_weight).to(edge_index.device)`
into
`adj = torch.sparse.FloatTensor(edge_index, edge_weight,(n_nodes, n_nodes)).to(edge_index.device)`

**Comment by emalgorithm** [comment]
Thanks, done!
